apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSManagedZone
metadata:
  name: kfname-goog-apis # {"type":"string","x-kustomize":{"setBy":"kpt","partialSetters":[{"name":"name","value":"kfname"}]}}
spec:
  description: "private zone for Google APIs"
  dnsName: "googleapis.com."
  visibility: private
  privateVisibilityConfig:
    networks:
    - networkRef:
        name: kfname # {"type":"string","x-kustomize":{"setter":{"name":"name","value":"kfname"}}}
---
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: kfname-goog-cname # {"type":"string","x-kustomize":{"setBy":"kpt","partialSetters":[{"name":"name","value":"kfname"}]}}
spec:
  name: "*.googleapis.com."
  type: "CNAME"
  ttl: 300
  managedZoneRef:
    name: kfname-goog-apis # {"type":"string","x-kustomize":{"setBy":"kpt","partialSetters":[{"name":"name","value":"kfname"}]}}
  rrdatas:
  - "restricted.googleapis.com."
---
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: kfname-goog-a # {"type":"string","x-kustomize":{"setBy":"kpt","partialSetters":[{"name":"name","value":"kfname"}]}}
spec:
  name: "restricted.googleapis.com."
  type: "A"
  ttl: 300
  managedZoneRef:
    name: kfname-goog-apis # {"type":"string","x-kustomize":{"setBy":"kpt","partialSetters":[{"name":"name","value":"kfname"}]}}
  rrdatas:
  - "199.36.153.4"
  - "199.36.153.5"
  - "199.36.153.6"
  - "199.36.153.7"
