apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSManagedZone
metadata:
  name: kfname-gcr # {"type":"string","x-kustomize":{"setBy":"kpt","partialSetters":[{"name":"name","value":"kfname"}]}}
spec:
  description: "private zone for GCR.io"
  dnsName: "gcr.io."
  visibility: private
  privateVisibilityConfig:
    networks:
    - networkRef:
        name: kfname # {"type":"string","x-kustomize":{"setter":{"name":"name","value":"kfname"}}}
---
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: kfname-gcr-cname # {"type":"string","x-kustomize":{"setBy":"kpt","partialSetters":[{"name":"name","value":"kfname"}]}}
spec:
  name: "*.gcr.io."
  type: "CNAME"
  ttl: 300
  managedZoneRef:
    name: kfname-gcr # {"type":"string","x-kustomize":{"setBy":"kpt","partialSetters":[{"name":"name","value":"kfname"}]}}
  rrdatas:
  - "gcr.io."
---
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: kfname-gcr-a # {"type":"string","x-kustomize":{"setBy":"kpt","partialSetters":[{"name":"name","value":"kfname"}]}}
spec:
  name: "gcr.io."
  type: "A"
  ttl: 300
  managedZoneRef:
    name: kfname-gcr # {"type":"string","x-kustomize":{"setBy":"kpt","partialSetters":[{"name":"name","value":"kfname"}]}}
  rrdatas:
  - "199.36.153.4"
  - "199.36.153.5"
  - "199.36.153.6"
  - "199.36.153.7"
