apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- ../../base
commonLabels:
  app.kubernetes.io/component: metadata
  app.kubernetes.io/instance: metadata-0.8.0
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/name: metadata
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: 0.8.0
kind: Kustomization
resources:
- application.yaml
